name: Deploy GH Pages

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: main
    - uses: actions/checkout@v2
      with:
        path: deploy
        ref: gh-pages
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm install -g grunt-cli
    - run: |
        cd main
        npm install
        grunt all

    - name: Cleanup old files
      run: |
        rm -rf deploy/downloads/
        rm -rf deploy/examples/
        rm -rf deploy/src/
        rm -rf deploy/index.md
        rm -rf deploy/LICENSE.md

    - name: Copy files
      run: |
        cp -R main/compiled deploy/downloads
        cp -R main/examples deploy
        cp -R main/images deploy
        cp -R main/src deploy
        cp main/index.md deploy
        cp main/LICENSE.md deploy

    - name: Commit back
      run: |
        cd deploy
        git config user.name github-actions[bot]
        git config user.email github-actions[bot]@users.noreply.github.com
        git add --all
        git commit -am "Generated by ${{ github.sha }}" || true
        git push
